/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_HelloJNI */

#ifndef _Included_com_company_HelloJNI
#define _Included_com_company_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_company_HelloJNI
	 * Method:    Sum
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_com_company_HelloJNI_Sum
	(JNIEnv*, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif